name: edugo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0  # Moved to main dependencies
  cupertino_icons: ^1.0.8
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  carousel_slider: ^5.0.0
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.0
  intl: ^0.20.0
  file_picker: ^8.0.0
  image_picker: ^0.8.7+3
  permission_handler: ^10.0.0
  http_parser: ^4.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/scholarship_1.png
